In [9]:
import numpy as np

In [10]:
# defining vectors
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])
c = np.array([0, 0, 1])

# Defining four objects
scalar = np.dot(a, b) #dot product
pseudoscalar = np.dot(c, np.cross(a, b))
polar_vector = c
axial_vector = np.cross(a, b)

#Symmetry operations
identity = np.array(
    [[1, 0, 0]
    ,[0, 1, 0]
    ,[0, 0, 1]])
inversion = np.array(
    [[-1, 0, 0]
    ,[0, -1, 0]
    ,[0, 0, -1]])
mirror_z = np.array(
    [[-1, 0, 0]
    ,[0, -1, 0]
    ,[0, 0, 1]])
mirror_y = np.array(
    [[-1, 0, 0]
    ,[0, 1, 0]
    ,[0, 0, -1]])
rotation_x_180 = np.array(
    [[1, 0, 0]
    ,[0, -1, 0]
    ,[0, 0, -1]])

print("identity = ", identity)
print("inversion = ", inversion)
print("mirror_z = ", mirror_z)
print("mirror_y = ", mirror_y)
print("rotation_x_180 = ", rotation_x_180)


identity =  [[1 0 0]
 [0 1 0]
 [0 0 1]]
inversion =  [[-1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]
mirror_z =  [[-1  0  0]
 [ 0 -1  0]
 [ 0  0  1]]
mirror_y =  [[-1  0  0]
 [ 0  1  0]
 [ 0  0 -1]]
rotation_x_180 =  [[ 1  0  0]
 [ 0 -1  0]
 [ 0  0 -1]]


## Table of Symmetry


| 1D object    | identity | inversion | mirror_y | rotation_x_180 |
|--------------|----------|-----------|----------|----------------|
| scalar       | 1        | 1         | 1        | 1              |
| pseudoscalar | 1        |-1         | 1        |-1              |
| polar vector | 1        | 1         |-1        |-1              |
| axial vector | 1        |-1         |-1        | 1              |


Notice that the square of any of these terms, i.e. $Q_i^2$, is even under all of the symmetry operations. This is a generalization of the multiplication rules "even times even is even" and "odd times odd is even" for each symmetry. You can think about this as a spring-mass system where the energy stored in the spring is $1/2 k x^2$. Each $Q_i$ is the coordinate of a mass, and $1/2 k$ is whatever the coefficient of that is that gives us units of energy. Are any terms $Q_i * Q_j$ possible? Why or why not? What about $Q_i * Q_j * Q_k$? These terms, if they exists, tell us how these "springs" can be coupled to each other.
#


##### Response
The terms $Q_i * Q_j$ are possible. If $Q_i$ describes the coordinate of a mass in a system, then $Q_i * Q_j$ would describe a system where two coordinate masses are coupled. This would require another kinetic energy term in order to describe the energy stored in the spring. It's important to note that these two Q terms, in a symmetry operation, would produce the same generalized multiplication rules as long as they are either both even or both odd. If one is even and one is odd then the symmetry table would be changed. It should then be possible to have three Q terms, with three descriptions of kinetic energy. In this configuration however the value of each Q, even or odd, matters less. If any Q value is odd, then the whole collective term is odd, and the only configuration where the term is even is if all values are even.
